# Usa uma imagem oficial do Python
FROM python:3.12-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o script hello.py para o container
COPY hello.py .

# Define o comando que será executado ao iniciar o container
CMD ["python", "hello.py"]
